openapi: 3.0.2
info:
  title: "API"
  version: "1.0.0"
  contact:
    name: Власов Айдар
    email: vlasov-a@surf.dev
  description: |
    Документ содержит описание API сервиса Стажерская Кухня
    
    <details>
    <summary>Специфические коды ошибок</summary>

    TODO: следует заполнить возможными ошибками в формате

    * `101` - UserBlocked, пользователь был заблокирован, 
    в **data** - количество секунд до разблокировки